// src/components/pricingcomponents/HeroSection.tsx
import { ChevronDown } from 'lucide-react';
import ParticleSphere from './ParticleSphere';

export default function HeroSection() {
  return (
    <section className="relative min-h-screen flex flex-col items-center justify-center px-4 overflow-hidden">
      <div className="absolute inset-0 bg-gradient-to-b from-slate-900 via-slate-800 to-slate-900">
        <ParticleSphere />
      </div>

      <div className="relative z-10 max-w-5xl mx-auto text-center">
        <h1 className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold text-white mb-6 leading-tight px-4">
          Finally, an AI Health Platform
          <br />
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-cyan-400">
            That Pays for Itself.
          </span>
        </h1>

        <p className="text-base sm:text-lg md:text-xl text-gray-300 max-w-3xl mx-auto leading-relaxed px-4">
          Discover how healthcare facilities like yours leverage iSenseHUB to
          not only enhance patient care but also unlock significant savings.
          Calculate your ROI below.
        </p>
      </div>

      <button
        onClick={() => window.scrollTo({ top: window.innerHeight, behavior: 'smooth' })}
        className="absolute bottom-8 left-1/2 -translate-x-1/2 text-white animate-bounce z-10"
        aria-label="Scroll down"
      >
        <ChevronDown size={40} />
      </button>
    </section>
  );
}

// src/components/pricingcomponents/HeroSection.vue
<template>
  <section class="relative min-h-screen flex flex-col items-center justify-center px-4 overflow-hidden">
    <div class="absolute inset-0 bg-gradient-to-b from-slate-900 via-slate-800 to-slate-900">
      <ParticleSphere />
    </div>

    <div class="relative z-10 max-w-5xl mx-auto text-center">
      <h1 class="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold text-white mb-6 leading-tight px-4">
        Finally, an AI Health Platform
        <br />
        <span class="text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-cyan-400">
          That Pays for Itself.
        </span>
      </h1>

      <p class="text-base sm:text-lg md:text-xl text-gray-300 max-w-3xl mx-auto leading-relaxed px-4">
        Discover how healthcare facilities like yours leverage iSenseHUB to
        not only enhance patient care but also unlock significant savings.
        Calculate your ROI below.
      </p>
    </div>

    <button
      @click="scrollDown"
      class="absolute bottom-8 left-1/2 -translate-x-1/2 text-white animate-bounce z-10"
      aria-label="Scroll down"
    >
      <svg class="w-10 h-10" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
      </svg>
    </button>
  </section>
</template>

<script setup lang="ts">
// Using inline SVG instead of lucide-vue-next
import ParticleSphere from './ParticleSphere.vue'

const scrollDown = () => {
  window.scrollTo({ top: window.innerHeight, behavior: 'smooth' })
}
</script>
